### ISSUE TITLE
bread crumb for child-route / sub-route

### ISSUE THREAD

**Issue by ayaanraj** [istrau2/aurelia-crumbs#1]
HI, i'm trying to implement this....

In my App.js

```javascript
export class App {
  configureRouter(config, router) {
    this.router = router;
    config.title = 'Aurelia';
config.map([
      {route: ['', 'home'], name: 'home',moduleId: 'home', nav: true, title: 'Home',breadcrumb: true },
      { route: 'contacts',  name: 'contacts',  moduleId: 'contacts', title: 'Contacts',nav: true,breadcrumb: true, settings: {
          subMenu: [
              {href: '#/email-contacts', title: 'Email-Contacts'},
              {href: '#/phone-contacts', title: 'Phone-Contacts'}  
          ]
      }},
      {route: 'services', name: 'services', moduleId: 'services',title: 'services',nav: true,breadcrumb: true},
      {route: 'email-contacts', name:'email-contacts', moduleId:'email-contacts',title: 'Email-Contacts',breadcrumb: true},
      {route: 'phone-contacts', name:'phone-contacts', moduleId:'phone-contacts',title: 'Phone-Contacts',breadcrumb: true}
 ]);
}
}
```

And In my App.html

<template>

 	    <ul >
 	      <li repeat.for="route of router.navigation" class="${route.isActive ? 'active' : ''}">
 	            <a href.bind="route.href" if.bind="!route.settings.subMenu">${route.title}</a>

 	            <a href.bind="route.href" class="dropdown-toggle" data-toggle="dropdown" if.bind="route.settings.subMenu">${route.title}<span class="caret"></span></a>

 	            <ul class="dropdown-menu" if.bind="route.settings.subMenu">
 	            	<li repeat.for="menu of route.settings.subMenu" class="${route.isActive ? 'active' : ''}">
			            <a href.bind="menu.href">${menu.title}</a>
			        </li>
 	            </ul>
 	    </ul>
 	 
<aurelia-crumbs config.bind="config"></aurelia-crumbs>
 <router-view></router-view>
 </template>

And everything works fine, but my problem is that, I want bread crumb to appear, this way ( Contacts > Email-Contact) when i go from Contacts to Email-Contact,  instead it is just showing Email-Contact directly

How can I solve this issue, please help me out.

**Comment by istrau2** [comment]
@ayaanraj 
The issue is that email-contacts is a sibling of the contacts route. The widget displays parent > child > grandchild and so on. If you want to display Contacts > Email-Contact you would need to make a Email-Contact a child route of the Contacts route. You can learn about child routes/routers here:

http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/2
