### ISSUE TITLE
Last instruction doesn't need to be a link

### ISSUE THREAD

**Issue by Kizmar** [istrau2/aurelia-crumbs#2]
Doesn't hurt anything, but maybe a "nice to have" type change: the last instruction in the crumbs doesn't need to be a link because you are already there.

[Link] \ [Link] \ Text

Edit: great custom element though, the one I was previously using didn't work as flawlessly as this one. :)

**Comment by istrau2** [comment]
Will fix as soon as I have time.

Edit: Thanks, I am glad it is working well.

**Comment by istrau2** [comment]
After thinking about this issue, I don't think it is a good idea.

Reason:
The aurelia router supports custom navigation strategies. It may be, that a developer would like to re-navigate to a route even if it is the current one and therefore sets up the router to function that way.

I think, in the case where an app is using the standard router and you would like to display the last link a little differently (to show that it does nothing), you can use some css to do that.
